--// File generated by F0x's Resources Generator 3.0.0 \\--

if ( SERVER ) then
	resource.AddFile( "materials/vgui/ttt/icon_ttt_harpoon.vmt" )
	resource.AddFile( "materials/vgui/ttt/icon_ttt_harpoon.vtf" )
	resource.AddFile( "models/weapons/ttt_harpoon/v_invisib.mdl" )
	resource.AddFile( "models/weapons/ttt_harpoon/w_ttt_harpoon.mdl" )
	resource.AddFile( "sound/weapons/ttt_harpoon/deploy.mp3" )
	resource.AddFile( "sound/weapons/ttt_harpoon/impact.mp3" )
	resource.AddFile( "sound/weapons/ttt_harpoon/nastystab.mp3" )
end